services:
  web:
    build:
      context: .
    container_name: mywebapp
    ports:
      - "80:80"        # Expose Apache (HTTP)
    volumes:
      - ./:/var/www/html  # Map your project files
      - ./cron:/cron      # Mount the cron directory
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - webnet
    command: >
      bash -c "cron && apachectl -D FOREGROUND"

  postgres:
    image: postgres:latest
    container_name: mydb
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Expose PostgreSQL (for psql access)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
